[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Projects"
pageRef = "posts"
weight = 10

[[main]]
name = "Exam Portfolio"
pageRef = "exam"
identifier = "LCjEWbroPp"
weight = 9_999

[[footer]]
none = "none"
